### ISSUE TITLE
Can't sync parachain blocks with Docker image

### ISSUE THREAD

**Issue by nazar-pc** [Phala-Network/khala-parachain#33]
I'm trying to run an archival node with following docker-compose.yml:
```yml
version: '2'

services:
  khala:
    image: phalanetwork/khala-node
    ports:
      - 19948:9944
    volumes:
      - ./khala:/root/data
    environment:
      NODE_ROLE: ARCHIVE
```

Relay chain blocks are synced, but not parachain blocks for some reason:
```
khala_1  | 2021-10-22 22:38:30 [Parachain] 💤 Idle (0 peers), best: #0 (0xd435…be8d), finalized #0 (0xd435…be8d), ⬇ 1.0kiB/s ⬆ 0.6kiB/s    
khala_1  | 2021-10-22 22:38:30 [Relaychain] ⚙️  Syncing 70.1 bps, target=#9772297 (32 peers), best: #29789 (0x9012…29cc), finalized #29696 (0xfdd0…790c), ⬇ 42.2kiB/s ⬆ 5.4kiB/s    
```

I have a bunch of full nodes of other parachains and they work fine, I only found an issue with Khala.
